language: ruby
sudo: false
cache: bundler
rvm:
  - 2.1.2
  - 2.2.2
  - 2.3.1
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
before_script:
  - mysql -e 'create database polymorpheus_test;'
