language: ruby
sudo: false
cache: bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - 2.2.2
gemfile:
  - gemfiles/3.0.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.0.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.1.2
      gemfile: gemfiles/5.0.gemfile
before_script:
  - mysql -e 'create database polymorpheus_test;'
